### ISSUE TITLE
Remove log to macro panel on load?

### ISSUE THREAD

**Issue by jpt** [justinpenner/TalkingLeaves#12]
Every time Glyphs is opened, `Loading TalkingLeaves plugin…` is logged to the macro panel. There's nothing inherently wrong with that, but because it's the only plugin I have that does it, it did initially make me wonder if there was some sort of issue with the plugin

**Comment by justinpenner** [comment]
Thanks, yeah that isn't necessary. FIxed in [ca4194d](https://github.com/justinpenner/TalkingLeaves/commit/ca4194ddb531409871a9e200ab4847e36e0b581f)
