### ISSUE TITLE
Select all glyphs for a language in the font view

### ISSUE THREAD

**Issue by jenskutilek** [justinpenner/TalkingLeaves#15]
Maybe it would be nice to have a button to select all present glyphs for a language in the Font view.

**Comment by justinpenner** [comment]
Great idea, that would be a good addition to the right-click context menu I'm planning to add to the languages list. See https://github.com/justinpenner/TalkingLeaves/issues/6#issuecomment-2067764923

**Comment by justinpenner** [comment]
Completed in 36b7e12

<img width="618" alt="image" src="https://github.com/justinpenner/TalkingLeaves/assets/46039243/c0ece602-ed86-4fb8-8086-62b92699acf8">
