### ISSUE TITLE
generate glyph rather than create glyph

### ISSUE THREAD

**Issue by jpt** [justinpenner/TalkingLeaves#5]
Many of the glyphs that can be added can be composed by glyphs automatically, if you go through the normal process of adding a glyph (e.g. add a glyph called `macute` and a composite with `m` and `acutecomb` will be created for you), but in Talking Leaves it starts out empty - would it be possible to generate?

**Comment by justinpenner** [comment]
Fixed in 12bd104. It will generate composites now whenever possible, using `GSLayer.makeComponents()` which I believe builds composites the same way as the Add Glyphs dialog and the _Glyph > Create Composite_ menu item.
